"""alembic set up

Revision ID: 963307225291
Revises: b072c3a7a6d8
Create Date: 2024-04-17 16:47:46.289585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '963307225291'
down_revision: Union[str, None] = 'b072c3a7a6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Enum('PENDING', 'VERIFIED', name='userstatus'), nullable=True))
    op.add_column('user', sa.Column('verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_token')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
